### PR TITLE
Better slot claiming strategy

### PR DESCRIPTION
**Pull request by WydD**
I think I handled this stuff more cleanly for slot claming.
Here is my scenario I used to test this out.

3 devices A, B, C
Steps:
- All are plugged -> selected slots [A,B]
- A is unplugged [empty,B]
- B claims left [B,empty]
- A is replugged [B,A]
- C claims left [C,A]
- C claims right [A,C]

Previous behaviour was
- All are plugged [A,B]
- A is unplugged [C,B] C claimed automatically which is a bit clunky
- B claims left [B,C]
- A claims left [A,B] the swap here was not clever because C still wants to play, which is the problem you raised I think

### CODE REVIEW

**Comment by WydD** [comment]
Quick thought: maybe we should release a tournament ready dll where you can't claim someone's port (imagine players switching places during a match... binding is good but we have no visual feedback like the Home menu on PS4). S basically: just do the first plugged, first player.

In terms of code it just consist in the result from read*InputControllerChange.

**Comment by dantarion** [comment]
Lets get this out there and see what people think. I think theres also a subset of people where my code I posted didn't work at ALL for them, so we will have to see what people think

**Comment by WydD** [comment]
Agreed

**Comment by WydD** [comment]
btw
Be sure to merge this branch first there is a bug that has been fixed in there (xinput slot selection using right)

**Comment by dantarion** [comment]
Sure! I will test compile this out tonight and push out a build! I want to set up a page to collect feedback somehow, I wonder what the best way to do that is?

**Comment by WydD** [comment]
Google forms? with a link in the readme / description of the release.

**Pull request merged**
